"""
cost_calculator.py

WHAT THIS FILE DOES (small why):
Two jobs:
  1. Turns physical measurements (material surface area, freight cost) into
     actual money (packaging cost + freight cost = total cost).
  2. Runs the WHOLE pipeline twice -- once the "current" (naive/manual) way,
     and once the "AI" (optimized) way -- and compares them side by side,
     which is exactly what the PDF's Module 7 "Current vs AI Comparison"
     dashboard needs.

WHY THIS MATTERS (big why):
This is the final step of the AI Logic cascade in the PDF:
  ... -> Compare Multiple Scenarios -> Recommend Lowest Cost Solution
And it's also what makes the whole system's value PROVABLE, not just
claimed. Without a real "current" baseline computed the same way (not a
made-up number), the "% improvement" figures would be fabricated. Here, the
baseline is generated by deliberately using naive/unoptimized versions of
the same pipeline, so the comparison is apples-to-apples and fully
explainable.
"""

from dataclasses import dataclass, asdict

from app.services.package_optimizer import calculate_volume, _surface_area, PackageDimensions
from app.services.carton_optimizer import optimize_carton, CANDIDATE_CARTON_SIZES_CM, CartonResult
from app.services.pallet_optimizer import optimize_pallet, PalletResult
from app.services.container_optimizer import evaluate_all_containers, recommend_best_container


# Material cost per cm2 of packaging surface -- simplified documented assumption.
# A real system would source these from supplier price lists.
MATERIAL_COST_PER_CM2_USD = {
    "paper": 0.004,
    "plastic": 0.006,
    "metal": 0.015,
}


def calculate_packaging_cost(surface_area_cm2: float, material: str, total_units: int) -> float:
    """
    cost = (material cost per cm2) x (surface area of ONE package) x (how many packages)
    Straightforward multiplication -- no optimization needed here, this is just
    converting a physical quantity (material area) into money.
    """
    rate = MATERIAL_COST_PER_CM2_USD.get(material.lower(), MATERIAL_COST_PER_CM2_USD["paper"])
    return round(rate * surface_area_cm2 * total_units, 2)


def _naive_current_package(tea_density_g_cm3: float, package_weight_g: float) -> PackageDimensions:
    """
    Simulates how a package is shaped WITHOUT optimization -- the "current"
    manual approach. In practice, manual packaging decisions often default to
    a simple cube-ish guess rather than solving for minimum material, so we
    model that here: same volume, but shape picked without searching for the
    least-material option (we deliberately use an unfavorable/simplistic
    aspect ratio to represent an untuned manual choice).
    """
    volume = calculate_volume(tea_density_g_cm3, package_weight_g)
    # naive manual guess: a flat, arbitrary ratio someone might pick without analysis
    w = h = volume ** (1 / 3) * 1.15   # arbitrarily 15% off-optimal, representing manual guesswork
    l = volume / (w * h)
    sa = _surface_area((l, w, h))
    return PackageDimensions(
        length_cm=round(l, 2), width_cm=round(w, 2), height_cm=round(h, 2),
        volume_cm3=round(volume, 2), surface_area_cm2=round(sa, 2),
        aspect_ratio=round(w / h, 3),
    )


def _naive_current_carton(package: PackageDimensions, package_weight_g: float) -> CartonResult:
    """
    Simulates manual carton selection: picks the FIRST candidate carton size
    that fits at least one package, without trying all 6 rotations (just the
    package's given orientation) and without comparing fill ratios. This
    mirrors how a manual process might just grab a "usual" carton size rather
    than solving for best fit.
    """
    from app.services.carton_optimizer import _pick_board_grade

    pl, pw, ph = package.length_cm, package.width_cm, package.height_cm
    for carton_dims in CANDIDATE_CARTON_SIZES_CM:
        cl, cw, ch = carton_dims
        n_l, n_w, n_h = int(cl // pl), int(cw // pw), int(ch // ph)
        units = n_l * n_w * n_h
        if units > 0:
            carton_volume = cl * cw * ch
            fill_ratio = round((units * package.volume_cm3) / carton_volume, 3)
            weight_kg = round((units * package_weight_g) / 1000, 2)
            return CartonResult(
                carton_length_cm=cl, carton_width_cm=cw, carton_height_cm=ch,
                units_per_carton=units, fill_ratio=fill_ratio,
                carton_weight_kg=weight_kg, board_grade=_pick_board_grade(weight_kg),
            )
    raise ValueError("Naive carton selection failed to fit package in any candidate size")


def run_current_vs_ai(tea_density_g_cm3: float, package_weight_g: float,
                       total_units: int, material: str = "paper") -> dict:
    """
    Runs the pipeline TWICE:
      - "current": naive versions of package + carton, first-fit container choice
      - "ai": fully optimized package + carton + pallet + container

    Returns a comparison dict with both sets of numbers AND percentage
    improvement for each metric -- directly matches the PDF's Module 7 table:
    Package Size, Carton Size, Units Per Carton, Cartons Per Pallet,
    Containers Required, Packaging Cost, Freight Cost, Total Cost.
    """
    # --- CURRENT (naive) pipeline ---
    current_package = _naive_current_package(tea_density_g_cm3, package_weight_g)
    current_carton = _naive_current_carton(current_package, package_weight_g)
    current_pallet = optimize_pallet(current_carton, pallet_type="EURO")
    current_container_options = evaluate_all_containers(current_pallet, current_carton, total_units)
    # naive approach doesn't compare options -- just uses the first available (20GP if possible)
    current_container = current_container_options[0]

    current_packaging_cost = calculate_packaging_cost(current_package.surface_area_cm2, material, total_units)
    current_total_cost = round(current_packaging_cost + current_container.freight_cost_usd, 2)

    # --- AI (optimized) pipeline ---
    from app.services.package_optimizer import generate_package_options
    ai_options = generate_package_options(tea_density_g_cm3, package_weight_g)
    ai_label, ai_package = ai_options[0]  # best (lowest material) option
    ai_carton = optimize_carton(ai_package, package_weight_g)
    ai_pallet = optimize_pallet(ai_carton, pallet_type="EURO")
    ai_container = recommend_best_container(ai_pallet, ai_carton, total_units)

    ai_packaging_cost = calculate_packaging_cost(ai_package.surface_area_cm2, material, total_units)
    ai_total_cost = round(ai_packaging_cost + ai_container.freight_cost_usd, 2)

    def pct_improve(current_val, ai_val, lower_is_better=True):
        if current_val == 0:
            return 0.0
        change = (current_val - ai_val) / current_val * 100
        return round(change if lower_is_better else -change, 1)

    return {
        "current": {
            "package": asdict(current_package),
            "carton": asdict(current_carton),
            "pallet": asdict(current_pallet),
            "container": asdict(current_container),
            "packaging_cost_usd": current_packaging_cost,
            "total_cost_usd": current_total_cost,
        },
        "ai": {
            "package": asdict(ai_package),
            "package_shape_label": ai_label,
            "carton": asdict(ai_carton),
            "pallet": asdict(ai_pallet),
            "container": asdict(ai_container),
            "packaging_cost_usd": ai_packaging_cost,
            "total_cost_usd": ai_total_cost,
        },
        "improvement_pct": {
            "package_surface_area": pct_improve(current_package.surface_area_cm2, ai_package.surface_area_cm2),
            "units_per_carton": pct_improve(current_carton.units_per_carton, ai_carton.units_per_carton, lower_is_better=False),
            "cartons_per_pallet": pct_improve(current_pallet.cartons_per_pallet, ai_pallet.cartons_per_pallet, lower_is_better=False),
            "containers_required": pct_improve(current_container.containers_required, ai_container.containers_required),
            "container_utilization": pct_improve(current_container.container_utilization, ai_container.container_utilization, lower_is_better=False),
            "packaging_cost": pct_improve(current_packaging_cost, ai_packaging_cost),
            "freight_cost": pct_improve(current_container.freight_cost_usd, ai_container.freight_cost_usd),
            "total_cost": pct_improve(current_total_cost, ai_total_cost),
        },
    }
